// Cards
export const GET_CARDS = 'GET_CARDS';
export const ADD_CARD = 'ADD_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const CARDS_LOADING = 'CARDS_LOADING';

// Groups
export const GET_GROUPS = 'GET_GROUPS';
export const GET_GROUP_BY_ID = 'GET_GROUP_BY_ID';
export const GET_GROUPLIST = 'GET_GROUPLIST';
export const ADD_GROUP = 'ADD_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const GROUPS_LOADING = 'GROUPS_LOADING';
export const CHANGE_CURRENT_GROUP = 'CHANGE_CURRENT_GROUP';

// Preferences
export const CHANGE_OVERLAY_STATUS = 'CHANGE_OVERLAY_STATUS';
export const CHANGE_CARDMODAL_STATUS = 'CHANGE_CARDMODAL_STATUS';
export const CHANGE_GROUPMODAL_STATUS = 'CHANGE_GROUPMODAL_STATUS';